sudo: false

language: scala

jdk:
  - openjdk11

matrix:
  include:
  - scala: 2.12.11
    env: DEPLOY=true
  - scala: 2.13.1
    env: DEPLOY=false

before_install:
  - export PATH=${PATH}:./vendor/bundle
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$DEPLOY" = "true" ]; then bash scripts/decrypt-keys.sh; fi

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

cache:
  directories:
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

script:
  - ./sbt "++${TRAVIS_SCALA_VERSION}!" clean coreJS/test lawsJS/test
  - if [[ "$TRAVIS_SCALA_VERSION" != 2.13.* ]]; then ./sbt "++${TRAVIS_SCALA_VERSION}!" mimaReportBinaryIssues; fi
  - if [[ "$TRAVIS_SCALA_VERSION" != 2.13.* ]]; then ./sbt "++${TRAVIS_SCALA_VERSION}!" docs/makeMicrosite; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$DEPLOY" = "true" ]; then bash scripts/publish.sh; fi
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always
