sudo: false

language: scala

scala:
  - 2.11.11
  - 2.10.6

env:
  - DEPLOY=false

jdk:
  - oraclejdk8

matrix:
  include:
  - scala: 2.12.3
    jdk: oraclejdk8
    env: DEPLOY=true
  - scala: 2.13.0-M4
    script:
    # TODO https://github.com/scoverage/scalac-scoverage-plugin/issues/225
    - ./sbt "++${TRAVIS_SCALA_VERSION}!" coreJS/test lawsJS/test coreJVM/test lawsJVM/test

before_install:
  - export PATH=${PATH}:./vendor/bundle
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$DEPLOY" = "true" ]; then bash scripts/decrypt-keys.sh; fi

install:
  - rvm use 2.2.5 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

cache:
  directories:
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

script:
  - ./sbt "++${TRAVIS_SCALA_VERSION}!" clean coreJS/test lawsJS/test
  - ./sbt "++${TRAVIS_SCALA_VERSION}!" clean coverage coreJVM/test lawsJVM/test coverageReport
  - ./sbt "++${TRAVIS_SCALA_VERSION}!" docs/makeMicrosite

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$DEPLOY" = "true" ]; then bash scripts/publish.sh; fi
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always
